common:
  one_wire:
    retries:
      EINVAL: 100
      ENOENT: 10
  interval: 60

  time_zone: Canberra
  start_of_meteorological_day: 9
  
  jqplot:
    seriesDefaults:
      showMarker: false
    grid:
      shadow: false
  
  flot:
    
  
  scale:
    flot:
      shadowSize: 0
      xaxis:
        mode: time
        monthNames:
          - January
          - February
          - March
          - April
          - May
          - June
          - July
          - August
          - September
          - October
          - November
          - December
  
  temperature_chart:
    flot:
      yaxis:
        min: -5
        max: 40
      lines:
        lineWidth: 3
      colors:
        - "#ff0000"

  rainfall_chart:
    flot:
      yaxis:
        min: 0
      lines:
        lineWidth: 3
      colors:
        - "#0000ff"
        
  
  daily_temperatures_chart:
    flot:
      line:
        show: false
      bars:
        show: true
        barWidth: 86400000
        lineWidth: 0
        align: center
        fill: 1
      yaxis:
        min: -10
        max: 45
      colors:
        - "#ff2222"
        - "#2222ff"
  
  daily_rainfall_chart:
    flot:
      lines:
        show: false
      bars:
        show: true
        barWidth: 86400000
        lineWidth: 0
        align: center
        fill: 1
      yaxis:
        min: 0
      colors:
        - "#0000ff"

development:
  one_wire:
    host: ip-address-of-one-wire-server

production:
  one_wire:
    host: localhost
  restart_observations: "monit restart weather"
