common:
  one_wire:
    host: localhost
    port: 4304
    units: celsius
    retries:
      EINVAL: 100
      ENOENT: 10

  time_zone: Canberra
  start_of_meteorological_day: 9

  jqplot:
    seriesDefaults:
      showMarker: false
    grid:
      shadow: false

  scale:
    jqplot:
      axes:
        xaxis:
          pad: 1.0
          renderer: $.jqplot.DateAxisRenderer
          tickOptions:
            showMark: false 

  temperature_chart:
    jqplot:
      axes:
        yaxis:
          min: -5
          max: 40
          tickInterval: 5
          tickOptions:
            showMark: false
            formatString: "%i &#186;C"
            formatString: "%i"

  rainfall_chart:
    jqplot:
      axes:
        yaxis:
          min: 0
          tickInterval: 2
          tickOptions:
            showMark: false
            formatString: "%.1f mm"
            formatString: "%.1f"

  daily_temperatures_chart:
    jqplot:
      axes:
        yaxis:
          min: -10
          max: 45
          tickInterval: 5
          tickOptions:
            showMark: false
            formatString: "%i &#186;C"
            formatString: "%i"
      seriesDefaults:
        renderer: $.jqplot.OHLCRenderer
        rendererOptions:
          tickLength: 0
          lineWidth: 1

production:
  restart_observations: "monit restart weather"
